/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hector.tpv.tpv.desktop.ui;

import com.hector.tpv.tpv.desktop.api.ApiClient;
import com.hector.tpv.tpv.desktop.model.Categoria;
import com.hector.tpv.tpv.desktop.model.ComandaRequest;
import com.hector.tpv.tpv.desktop.model.Mesa;
import com.hector.tpv.tpv.desktop.model.MesaAbierta;
import com.hector.tpv.tpv.desktop.model.Producto;
import com.hector.tpv.tpv.desktop.model.Ticket;
import com.hector.tpv.tpv.desktop.model.UsuarioSesion;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.DefaultListModel;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author hecto
 */
public class TpvVentanaPrincipal extends javax.swing.JFrame {

    private final ApiClient api = ApiClient.fromProps();
    private final DefaultListModel<Mesa> modeloMesas = new DefaultListModel<>();
    private final DefaultListModel<Producto> modeloProductos = new DefaultListModel<>();
    private final ModeloTablaCarrito modeloCarrito = new ModeloTablaCarrito();
    private final ModeloTablaAbierto modeloAbierto = new ModeloTablaAbierto();

    private volatile boolean agregando = false;
    private volatile boolean enviando = false;
    private volatile boolean cobrando = false;

    private Mesa mesaActual = null;
    private Timer timerMesas;
    private UsuarioSesion usuarioSesion;

    public TpvVentanaPrincipal(UsuarioSesion usuarioSesion) {
        this.usuarioSesion = usuarioSesion;
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        ajustarPermisos();
        initLogica();
        instalarAccionesUI();
    }

    public TpvVentanaPrincipal() {
        this(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMesas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaProductos = new javax.swing.JList<>();
        btnEfectivo = new javax.swing.JButton();
        btnTarjeta = new javax.swing.JButton();
        cbCategoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaAbierto = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        lblTotalAbierto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnAgregar = new javax.swing.JButton();
        btnCierreTurno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Mesas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Abierto");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Productos");

        listaMesas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        listaMesas.setAutoscrolls(false);
        jScrollPane1.setViewportView(listaMesas);

        listaProductos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jScrollPane2.setViewportView(listaProductos);

        btnEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnEfectivo.setText("Efectivo");
        btnEfectivo.setPreferredSize(new java.awt.Dimension(150, 75));

        btnTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnTarjeta.setText("Tarjeta");
        btnTarjeta.setPreferredSize(new java.awt.Dimension(150, 75));

        cbCategoria.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Categorias");

        tablaAbierto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tablaAbierto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaAbierto);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Nueva Comanda");

        btnEnviar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setPreferredSize(new java.awt.Dimension(150, 75));

        tablaCarrito.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tablaCarrito);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTotal.setText("jLabel6");

        lblTotalAbierto.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTotalAbierto.setText("jLabel6");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnAgregar.setText("Añadir");
        btnAgregar.setPreferredSize(new java.awt.Dimension(150, 75));

        btnCierreTurno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCierreTurno.setText("<html>CIERRE<br>DE TURNO</html>");
        btnCierreTurno.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCierreTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(6, 6, 6)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalAbierto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal))
                    .addComponent(btnCierreTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TpvVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TpvVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TpvVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TpvVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TpvVentanaPrincipal().setVisible(true);
            }
        });
    }

    private void initLogica() {

        listaMesas.setModel(modeloMesas);
        listaProductos.setModel(modeloProductos);
        tablaCarrito.setModel(modeloCarrito);
        tablaAbierto.setModel(modeloAbierto);

        tablaCarrito.setRowHeight(28);
        tablaAbierto.setRowHeight(28);
        tablaCarrito.setFillsViewportHeight(true);
        tablaAbierto.setFillsViewportHeight(true);

        listaMesas.setFixedCellWidth(140);
        listaMesas.setCellRenderer(new MesaListCellRenderer());

        listaProductos.setFixedCellWidth(300);

        lblTotal.setText("Total: 0.00€");
        lblTotalAbierto.setText("Abierto: 0.00€");

        listaMesas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    mesaActual = listaMesas.getSelectedValue();
                    modeloCarrito.getLineas().clear();
                    modeloCarrito.fireTableDataChanged();
                    lblTotal.setText("Total: 0.00€");
                    cargarAbierto();
                    actualizarEstadoControles();
                }
            }
        });

        btnAgregar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                agregarProductoSeleccionado();
            }
        });

        btnEnviar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                enviarComanda();
                actualizarEstadoControles();
            }
        });

        btnEfectivo.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                cobrarActual("EFECTIVO");
            }
        });

        btnTarjeta.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                cobrarActual("TARJETA");
            }
        });

        btnCierreTurno.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ejecutarCierreTurno();
            }
        });

        cbCategoria.addActionListener(e -> onCategoriaChange());

        SwingUtilities.invokeLater(() -> {
            cargarMesas();
            cargarCategorias();
            iniciarTimerMesas();
        });

        tablaCarrito.setAutoCreateColumnsFromModel(false);
        tablaAbierto.setAutoCreateColumnsFromModel(false);
        tablaCarrito.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        tablaAbierto.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        listaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

    }

    private void cargarMesas() {
        try {
            List<Mesa> m = api.getMesas();
            modeloMesas.clear();
            for (Mesa x : m) {
                modeloMesas.addElement(x);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error cargando mesas: " + ex.getMessage());
        }
    }

    private void onCategoriaChange() {
        Object sel = cbCategoria.getSelectedItem();
        modeloProductos.clear();
        try {
            if (sel instanceof Categoria) {
                Categoria c = (Categoria) sel;
                List<Producto> productos;
                if (c.getId() == null) {
                    productos = api.getProductos(); // ya lo tienes implementado
                } else {
                    productos = api.getProductosPorCategoria(c.getId());
                }
                for (Producto p : productos) {
                    modeloProductos.addElement(p);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error cargando productos: " + ex.getMessage());
        }
        actualizarEstadoControles();
    }

    private void cargarCategorias() {
        try {
            List<Categoria> cats = api.getCategorias();
            cbCategoria.removeAllItems();
            cbCategoria.addItem(new Categoria() {
                {
                    setId(null);
                    setNombre("Todas");
                }
            });
            for (Categoria c : cats) {
                cbCategoria.addItem(c);
            }
            cbCategoria.setSelectedIndex(0);
        } catch (IOException ex) {
            Logger.getLogger(TpvVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(TpvVentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarAbierto() {
        if (mesaActual == null) {
            modeloAbierto.setDatos(java.util.List.of());
            lblTotalAbierto.setText("Abierto: 0.00€");
            return;
        }
        try {
            MesaAbierta abierto = api.getMesaAbierta(mesaActual.getId());
            modeloAbierto.setDatos(abierto.getItems());
            lblTotalAbierto.setText(String.format("Abierto: %.2f€", abierto.getTotal()));
        } catch (Exception ex) {
            modeloAbierto.setDatos(java.util.List.of());
            lblTotalAbierto.setText("Abierto: 0.00€");
            JOptionPane.showMessageDialog(this, "Error cargando abierto: " + ex.getMessage());
        }
    }

    private void enviarComanda() {
        if (enviando) {
            return;
        }
        if (mesaActual == null) {
            JOptionPane.showMessageDialog(this, "Selecciona una mesa primero");
            return;
        }
        if (modeloCarrito.getLineas().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay productos en la comanda");
            return;
        }

        enviando = true;
        btnEnviar.setEnabled(false);
        try {
            var c = new ComandaRequest();
            c.setMesaId(mesaActual.getId());

            Long camareroId = 1L;
            if (usuarioSesion != null && usuarioSesion.getId() != null) {
                camareroId = usuarioSesion.getId();
            }
            c.setCamareroId(camareroId);

            c.setLineas(modeloCarrito.getLineas());

            var id = api.postComanda(c);

            JOptionPane.showMessageDialog(this, id.isPresent()
                    ? "Comanda enviada. ID=" + id.get()
                    : "Comanda enviada.");

            modeloCarrito.clear();
            lblTotal.setText("Total: 0.00€");

            SwingUtilities.invokeLater(this::cargarAbierto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error enviando comanda: " + ex.getMessage());
        } finally {
            enviando = false;
            actualizarEstadoControles();
            btnEnviar.setEnabled(true);
        }
    }

    private void instalarAccionesUI() {
        listaProductos.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    agregarProductoSeleccionado();
                }
            }
        });
        listaProductos.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    agregarProductoSeleccionado();
                }
            }
        });

        InputMap im = tablaCarrito.getInputMap(JTable.WHEN_FOCUSED);
        ActionMap am = tablaCarrito.getActionMap();
        im.put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), "borrarLineas");
        am.put("borrarLineas", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                int[] rows = tablaCarrito.getSelectedRows();
                if (rows != null && rows.length > 0) {
                    for (int i = rows.length - 1; i >= 0; i--) {
                        int r = rows[i];
                        if (r >= 0 && r < modeloCarrito.getLineas().size()) {
                            modeloCarrito.getLineas().remove(r);
                        }
                    }
                    modeloCarrito.fireTableDataChanged();
                    recalcularTotal();
                    actualizarEstadoControles();
                }
            }
        });

        modeloCarrito.addTableModelListener(new TableModelListener() {
            public void tableChanged(TableModelEvent e) {
                if (e.getType() == TableModelEvent.UPDATE) {
                    recalcularTotal();
                }
                actualizarEstadoControles();
            }
        });

        try {
            TableColumn colCant = tablaCarrito.getColumnModel().getColumn(1);
            tablaCarrito.setSurrendersFocusOnKeystroke(true);
            colCant.setPreferredWidth(70);
        } catch (Exception ignore) {
        }

        JTableHeader h1 = tablaCarrito.getTableHeader();
        JTableHeader h2 = tablaAbierto.getTableHeader();
        h1.setFont(h1.getFont().deriveFont(20f));
        h2.setFont(h2.getFont().deriveFont(20f));
        h1.setPreferredSize(new Dimension(h1.getPreferredSize().width, h1.getFont().getSize() + 8));
        h2.setPreferredSize(new Dimension(h2.getPreferredSize().width, h2.getFont().getSize() + 8));

        actualizarEstadoControles();
    }

    private void agregarProductoSeleccionado() {
        if (agregando) {
            return;
        }
        agregando = true;
        try {
            Producto p = listaProductos.getSelectedValue();
            if (p == null || mesaActual == null) {
                return;
            }

            modeloCarrito.addProducto(p);

            recalcularTotal();
            actualizarEstadoControles();

            if (tablaCarrito.getRowCount() > 0) {
                int last = tablaCarrito.getRowCount() - 1;
                tablaCarrito.getSelectionModel().setSelectionInterval(last, last);
                tablaCarrito.scrollRectToVisible(tablaCarrito.getCellRect(last, 0, true));
            }
        } finally {
            agregando = false;
        }
    }

    private void recalcularTotal() {
        lblTotal.setText(String.format("Total: %.2f€", modeloCarrito.getTotal()));
    }

    private void actualizarEstadoControles() {
        boolean mesaOk = mesaActual != null;
        boolean carritoOk = !modeloCarrito.getLineas().isEmpty();
        boolean abiertoOk = modeloAbierto.getRowCount() > 0;
        btnAgregar.setEnabled(mesaOk && listaProductos.getSelectedIndex() != -1);
        btnEnviar.setEnabled(mesaOk && carritoOk);
        btnTarjeta.setEnabled(mesaOk && (carritoOk || abiertoOk));
        btnEfectivo.setEnabled(mesaOk && (carritoOk || abiertoOk));
    }

    private void cobrarActual(String metodoPago) {
        if (cobrando) {
            return;
        }
        if (mesaActual == null) {
            JOptionPane.showMessageDialog(this, "Selecciona una mesa primero");
            return;
        }
        cobrando = true;
        btnEfectivo.setEnabled(false);
        btnTarjeta.setEnabled(false);
        try {
            Ticket ticket = api.cobrarMesa(mesaActual.getId(), metodoPago);

            java.nio.file.Path destinoPdf = null;
            try {
                destinoPdf = api.descargarTicketPdf(ticket.getId());
            } catch (Exception exDescarga) {
                JOptionPane.showMessageDialog(this, "Cobrado, pero error al descargar el PDF: " + exDescarga.getMessage());
            }

            if (destinoPdf != null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Cobrado. Ticket " + ticket.getId()
                        + " Total: " + String.format("%.2f€", ticket.getTotal())
                        + "\nPDF guardado en:\n" + destinoPdf.toString()
                );
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "Cobrado. Ticket " + ticket.getId()
                        + " Total: " + String.format("%.2f€", ticket.getTotal())
                );
            }

            modeloCarrito.getLineas().clear();
            modeloCarrito.fireTableDataChanged();
            lblTotal.setText("Total: 0.00€");
            javax.swing.SwingUtilities.invokeLater(this::cargarAbierto);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al cobrar: " + ex.getMessage());
        } finally {
            cobrando = false;
            actualizarEstadoControles();
            btnEfectivo.setEnabled(true);
            btnTarjeta.setEnabled(true);
        }
    }

    private void ejecutarCierreTurno() {
        try {
            com.hector.tpv.tpv.desktop.model.CierreTurno cierre = api.cerrarTurno();

            java.nio.file.Path destinoPdf = null;
            try {
                destinoPdf = api.descargarCierreTurnoPdf(cierre.getId());
            } catch (Exception exDescarga) {
                JOptionPane.showMessageDialog(this,
                        "Cierre realizado, pero error al descargar el PDF: " + exDescarga.getMessage());
            }

            String msg = "Cierre de turno realizado.\n"
                    + "Comandas cerradas: " + cierre.getNumComandas() + "\n"
                    + String.format("Base imponible: %.2f€\n", cierre.getBaseTotal())
                    + String.format("IVA: %.2f€\n", cierre.getIvaTotal())
                    + String.format("Total: %.2f€\n", cierre.getTotal())
                    + "Desde: " + cierre.getDesde() + "\n"
                    + "Hasta: " + cierre.getHasta();

            if (destinoPdf != null) {
                msg = msg + "\n\nPDF guardado en:\n" + destinoPdf.toString();
            }

            JOptionPane.showMessageDialog(this, msg);

            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    cargarAbierto();
                }
            });
        } catch (IllegalStateException ex) {
            JOptionPane.showMessageDialog(this, "No hay comandas cobradas para cerrar.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error en el cierre de turno: " + ex.getMessage());
        }
    }

    private void iniciarTimerMesas() {
        timerMesas = new Timer(5000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                refrescarEstadoMesas();
            }
        });
        timerMesas.start();
    }

    private void refrescarEstadoMesas() {
        try {
            List<Mesa> servidor = api.getMesas();

            for (int i = 0; i < modeloMesas.size(); i++) {
                Mesa actual = modeloMesas.getElementAt(i);
                Long id = actual.getId();

                for (Mesa m : servidor) {
                    if (m.getId().equals(id)) {
                        actual.setOcupada(m.isOcupada());
                        break;
                    }
                }
            }

            listaMesas.repaint();
        } catch (Exception ex) {
        }
    }

    private void ajustarPermisos() {
        boolean esAdmin = false;

        if (usuarioSesion != null) {
            String rol = usuarioSesion.getRol();
            if (rol != null && rol.equalsIgnoreCase("ADMIN")) {
                esAdmin = true;
            }
        }

        btnCierreTurno.setVisible(esAdmin);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCierreTurno;
    private javax.swing.JButton btnEfectivo;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JComboBox<Categoria> cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalAbierto;
    private javax.swing.JList<Mesa> listaMesas;
    private javax.swing.JList<Producto> listaProductos;
    private javax.swing.JTable tablaAbierto;
    private javax.swing.JTable tablaCarrito;
    // End of variables declaration//GEN-END:variables
}
